regex-checker

diff --git a/bash-scripts-windows/regex-checker b/bash-scripts-windows/regex-checker
--- a/bash-scripts-windows/regex-checker
+++ b/bash-scripts-windows/regex-checker
@@ -4,9 +4,9 @@
 # exit status, error codes and script usage                #
 #+========================================================+#
 
-SUCCESS=0		# success exit code
-E_NOARGS=65		# no arguments passed to script
-E_NOMATCH=66	# url not matched by regular expression
+SUCCESS=0     # success exit code
+E_NOARGS=65   # no arguments passed to script
+E_NOMATCH=66  # url not matched by regular expression
 
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url]"
 
@@ -16,9 +16,9 @@ script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/vid
 #+========================================================+#
 
 if [[ "$1" =~ \.txt$ ]]; then # + text file passed as first argument to script
-	videourl=$(cat "$1")       # - cat the text file to extract the url
+   videourl=$(cat "$1")       # - cat the text file to extract the url
 else
-	videourl="$1"              # url is on the command line
+   videourl="$1"              # url is on the command line
 fi
 
 #+========================================================+#
@@ -31,13 +31,13 @@ fi
 first_arg_validated="^(http|https|rtmp|rtmpe)://*"    # matches: http|https|rtmp|rtmpe
 
 if [[ $# -eq 1 ]]; then                               # + one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
-		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
-		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
-	fi
+   if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
+      printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
+      exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
+   fi
 else [[ $# -eq 0 ]]                                   # + no arguments are passed to the script
    printf "%s\n" "$script_usage"                      # - display script usage
-	exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
+   exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
 fi
 
 shopt -s extglob # enable shell globbing 
