rip-record-reconnect with bash functions

diff --git a/bash-scripts-windows/rip-record-reconnect b/bash-scripts-windows/rip-record-reconnect
--- a/bash-scripts-windows/rip-record-reconnect
+++ b/bash-scripts-windows/rip-record-reconnect
@@ -116,6 +116,45 @@ cookienltid=$(printf "%s" "$videourl" | grep -Eo 'nltid=[a-zA-Z0-9&%_*=]*')
 cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*[^/]' | sed 's/^http\(\|s\):\/\///g')
 
 #+========================================================+#
+# recording functions using ffmpeg and rtmpdump           +#
+#+========================================================+#
+
+# ffmpeg function
+record () {
+printf "%s\n" "Recording: '$videourl'"
+count=0 # set count to zero
+while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
+recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
+ffmpeg \
+-reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
+-hide_banner -loglevel error $2 $3 $4 $5 -i "$1" -c:v copy -c:a copy $tflag $duration "$recordingfile"
+if [[ $? -eq 0 ]]; then
+    break # break out of the while loop
+    exit "$SUCCESS" # exit with $success error code
+fi
+let count=count+1 # increment count
+sleep 1
+done
+}
+
+# rtmpdump function
+record_rtmp () {
+printf "%s\n" "Recording: '$videourl'"
+count=0 # set count to zero
+while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
+recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
+rtmpdump -q -i "$1" | ffmpeg \
+-hide_banner -loglevel error -i - -c:v copy -c:a copy $tflag $duration "$recordingfile"
+if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
+   break # break out of the while loop
+   exit "$SUCCESS" # exit with $success error code
+fi
+let count=count+1 # increment count
+sleep 1
+done
+}
+
+#+========================================================+#
 # case statement with regular expression                   #
 # + to execute ffmpeg commands based on matching url       #
 #+========================================================+#
@@ -123,209 +162,43 @@ cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*
 case "$videourl" in
   $videofile)         # video file
        printf "%s\n" 'url matches: $videofile bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -i "$videourl" -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record "$videourl";;
   $m3u8)              # m3u8 playlist
        printf "%s\n" 'url matches: $m3u8 bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -i "$videourl" \
-       -c:v copy -c:a copy $tflag $duration "$recordingfile" 2>&1 | sed '/\[/d'
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record "$videourl";;
   $cookiem3u8)        # cookie m3u8
        printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -loglevel panic -cookies "$cookienltid; path=/; $cookiedomain;" -i "$videourl" \
-       -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+		 record "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
   $videoqmark)         # video link and question mark
        printf "%s\n" 'url matches: $videoqmark bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -loglevel error -i "$videourl" \
-       -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+		 record "$videourl";;
   $xforward)          # xforward
        printf "%s\n" 'url matches: $xforward bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -headers 'X-Forwarded-For: '"$xforwardip"''$'\r\n' -i "$videofile_grep" \
-       -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
   $useref)            # useragent referer
        printf "%s\n" 'url matches: $useref bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -user-agent "$useragent" -headers 'Referer: '"$referer"''$'\r\n' \
-       -i "$videofile_grep" -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
   $viduseragent)     # user agent 
        printf "%s\n" 'url matches: $viduseragent bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -loglevel error -user-agent "$useragent" -i "$videofile_grep" \
-       -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record "$videofile_grep" -user-agent "$useragent";;
   $useragentreferer) # useragent referer
        printf "%s\n" 'url matches: $useragentreferer bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -loglevel error -user-agent "$useragent" \
-       -headers 'Referer: '"$referer"''$'\r\n' -i "$videofile_grep" \
-       -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
   $refuseragent)      # referer user agent
        printf "%s\n" 'url matches: $refuseragent bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -loglevel error -headers 'Referer: '"$referer"''$'\r\n' \
-       -user-agent "$useragent" -i "$videofile_grep" -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
   $rtmp)              # rtmp
        printf "%s\n" 'url matches: $rtmp bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       rtmpdump -q -i "$videourl" | ffmpeg \
-       -hide_banner -i - -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record_rtmp "$videourl";;
   $cookiem3u8uagent)  # cookie m3u8 useragent
        printf "%s\n" 'url matches: $cookiem3u8uagent bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -user-agent "$useragent2" \
-       -cookies "$cookieurl; path=/; $cookiedomain;" -i "$videofile_grep" \
-       -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+       record "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
   $http)              # http
        printf "%s\n" 'url matches: $http bash pattern'
-       printf "%s\n" "Recording: a'$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-       -hide_banner -i "$videourl" -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+		 record "$videourl";;
   *)                  # wildcard
        printf "%s\n" 'url matches: * bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$USERPROFILE/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv"
-       ffmpeg -hide_banner -i "$videourl" -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$success" # exit with $success error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
+		 record "$videourl";;
 esac \
 && [[ -f "$notify" ]] && [[ $? -eq 0 ]] \
 && notify-send "Finished Recording" "$videourl"
