m3u8-link-checker now accepts m3u files

diff --git a/bash-scripts/m3u8-link-checker b/bash-scripts/m3u8-link-checker
--- a/bash-scripts/m3u8-link-checker
+++ b/bash-scripts/m3u8-link-checker
@@ -1,48 +1,30 @@
 #!/bin/bash
 
 #+==========================================================+#
-# m3u8-link-checker check m3u8 for working links            +#
+# m3u8-link-checker check m3u8 - m3u files for working links #
 #+==========================================================+#
 
-# diagram of how the script works
-# [m3u8-link-checker] > [(m3u8 file)] > [ffprobe]
-
-#+=========================================================+#
-# exit status and error codes                               #
-#+=========================================================+#
-
+# exit status and error codes
 SUCCESS=0      # success exit code
-E_NOARGS=65    # no arguments passed to script
+E_WRONGARGS=65 # wrong number of arguments passed to script
 E_WRONGFILE=66 # wrong file passed to script
 
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
-
-script_usage="Usage: $(basename "$0") [m3u8 file]"
+# script usage
+script_usage="Usage: $(basename "$0") [m3u8 or m3u file]"
 
 #+========================================================+#
-# check if first argument is m3u8 file                    +#
+# check arguments passed to scripts                        #
 #+========================================================+#
 
-if [[ "$1" =~ \.m3u8$ ]]; then         # + m3u8 file passed as first argument to script
+# check number of arguments passed to script and exit if not correct
+[[ $# -eq 1 ]] || { printf "%s\n" "$script_usage"; exit "$E_WRONGARGS"; }
+
+if [[ "$1" =~ \.m3u8?$ ]]; then        # + m3u8 file passed as first argument to script
     file="$1"                          # - filename is first argument passed to script
-    outfile="${file%%.*}-checked.m3u8" # - get filename without extension
+    outfile="${file%%.*}-checked.${file##*.}" # - get filename and extension
 else
-   printf "%s\n" "'$1' invalid input"  # + no arguments are passed to the script
-   printf "%s\n" "$script_usage"       # - display script usage
+   printf "%s\n%s\n" "'$1' invalid input" "$script_usage" # + no arguments are passed to the script
    exit "$E_WRONGFILE"                 # - exit with E_WRONGFILE error code
-fi
-
-#+========================================================+#
-# check number of arguments passed to script               #
-#+========================================================+#
-
-if [[ $# -ne 1 ]]; then               # + if one agrument isnt passed to script
-   printf "%s\n" "'$1' invalid input" # - print argument passed to script and invalid input
-   printf "%s\n" "$script_usage"      # - print script usage
-   exit "$E_NOARGS"                   # - exit with E_NOARGS error code
 fi
 
 #+========================================================+#
@@ -52,15 +34,11 @@ fi
 printf "%s\n" "Checking $file for working links"
 printf "%s\n" "#EXTM3U" > "$outfile"
 
-while IFS= read -r line               # while read m3u8 file check links with ffprobe
+while IFS= read -r line               # while read m3u8 or m3u file check links with ffprobe
 do 
   link=$(printf "%s\n" "$line" | grep -Eo '(http|https)://[a-zA-Z0-9:0-9./?=_@&%|()[:blank:],;-]*' | grep -v '.[(jpg|png|gif|svg)]$')
   [[ $? -eq 0 ]] && ffprobe -hide_banner "$link"
   [[ $? -eq 0 ]] && grep -B 1 "$link" "$file" 2>/dev/null | sed -e '/--/d' >> "$outfile"
 done <"$file"
 
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+exit "$SUCCESS" # exit 
