regex-checker comment style

diff --git a/bash-scripts/regex-checker b/bash-scripts/regex-checker
--- a/bash-scripts/regex-checker
+++ b/bash-scripts/regex-checker
@@ -1,17 +1,12 @@
 #!/bin/bash
 
 #+=========================================================+#
-# exit status and error codes                               #
+# exit status, error codes and script usage                 #
 #+=========================================================+#
 
 SUCCESS=0		# success exit code
 E_NOARGS=65		# no arguments passed to script
 E_NOMATCH=66	# url not matched by regular expression
-
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
 
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url]"
 
@@ -34,8 +29,8 @@ else
 fi
 
 #+========================================================+#
-# check if 1 argument is  passed to script                 #
-# + and validate user input                                #
+# check if 1 or 3 arguments are passed to script           #
+# + validate user input and enable shell globing           #
 #+========================================================+#
 
 if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
@@ -48,11 +43,7 @@ else [[ $# -eq 0 ]]                                   # - no arguments are passe
 	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
 fi
 
-#+========================================================+#
-# enable shell globbing for pattern matching               #
-#+========================================================+#
-
-shopt -s extglob 
+shopt -s extglob # enable shell globbing 
 
 #+========================================================+#
 # case statement switch on pattern match                   #
@@ -92,14 +83,5 @@ case "$videourl" in
 	*) printf "%s\n%s\n" 'url matches: * bash pattern' "url checked: '$videourl'";;
 esac 
 
-#+========================================================+#
-# turn off shell globbing                                  #
-#+========================================================+#
-
-shopt -u extglob 
-
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+shopt -u extglob # turn off shell globbing
+exit "$SUCCESS" # exit status SUCCESS if script runs without errors
