valicate

diff --git a/bash-scripts/rip-record b/bash-scripts/rip-record
--- a/bash-scripts/rip-record
+++ b/bash-scripts/rip-record
@@ -7,11 +7,13 @@
 SUCCESS=0
 E_NOARGS=65
 script_usage="Usage: $(basename $0) [video url] {[-t] [00:00:00]}"
+
+# validate user input
 first_arg_validated="^(http|https|rtmp|rtmpe)://*"
 second_arg_validated="^-t$"
 third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$"
 
-# ffmpeg duration 2nd and 3rd arguments passed to script
+# ffmpeg duration 
 tflag="$2"
 duration="$3" 
 
@@ -21,10 +23,11 @@ duration="$3"
 [[ "$1" =~ \.txt$ ]] && videourl=$(cat "$1") || videourl="$1"
 
 # first arg check
-#if ! [[ $videourl =~ $first_arg_validated ]]; then
-#   printf "%s\n" "$script_usage"
-#	exit "$E_NOARGS" 
-#fi
+if ! [[ $videourl =~ $first_arg_validated ]]; then
+	printf "%s\n" "$videourl = invalid option"
+   printf "%s\n" "$script_usage"
+	exit "$E_NOARGS" 
+fi
 
 # second arg check
 #if ! [[ $2 =~ $second_arg_validated ]]; then
