comments

diff --git a/bash-scripts/rip-record b/bash-scripts/rip-record
--- a/bash-scripts/rip-record
+++ b/bash-scripts/rip-record
@@ -58,19 +58,19 @@ fi
 
 if [[ $# -eq 1 ]]; then											# - one argument is passed to the script
 	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"			# + display user input with error message
+		printf "%s\n" "'$videourl' invalid input"			# + display invalid user input with error message
 		printf "%s\n" "$script_usage"							# + display script usage
 		exit "$E_NOMATCH"											# + exit with E_NOMATCH error code
 	fi
 elif [[ $# -eq 3 ]]; then										# - three arguments are passed to the script, validate user input
 	if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
-		printf "%s\n" "'$1 $2 $3' invalid input" 
-		printf "%s\n" "$script_usage"	
-		exit "$E_NOMATCH"
+		printf "%s\n" "'$1 $2 $3' invalid input" 			# + display invalid user input with error message
+		printf "%s\n" "$script_usage"							# + display script usage
+		exit "$E_NOMATCH"											# + exit with E_NOMATCH error code
 	fi
 else [[ $# -eq 0 ]]												# - no arguments are passed to the script
    printf "%s\n" "$script_usage"								# + display script usage
-	exit "$E_NOARGS" 												# + exit
+	exit "$E_NOARGS" 												# + exit with E_NOARGS error code
 fi
 
 #+========================================================+#
