error feedback

diff --git a/bash-scripts/rip-record b/bash-scripts/rip-record
--- a/bash-scripts/rip-record
+++ b/bash-scripts/rip-record
@@ -28,15 +28,17 @@ duration="$3"
 
 # second arg check
 #if ! [[ $2 =~ $second_arg_validated ]]; then
+#	printf "%s\n" "$2 = invalid option"
 #   printf "%s\n" "$script_usage"
 #	exit "$E_NOARGS" 
 #fi
 
 # third arg check
-if ! [[ $3 =~ $third_arg_validated ]]; then
-   printf "%s\n" "$script_usage"
-	exit "$E_NOARGS" 
-fi
+#if ! [[ $3 =~ $third_arg_validated ]]; then
+#	printf "%s\n" "$3 = invalid option"
+#   printf "%s\n" "$script_usage"
+#	exit "$E_NOARGS" 
+#fi
 
 
 # enable shell globbing for pattern matching
