bash pattern matching

diff --git a/bash-scripts/rip-stream b/bash-scripts/rip-stream
--- a/bash-scripts/rip-stream
+++ b/bash-scripts/rip-stream
@@ -8,79 +8,79 @@
 # [rip-stream] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [ffmpeg]
 
 #+=========================================================+#
-# exit status and error codes											#
+# exit status and error codes                               #
 #+=========================================================+#
 
-SUCCESS=0		# success exit code
-E_NOARGS=65		# no arguments passed to script
+SUCCESS=0      # success exit code
+E_NOARGS=65    # no arguments passed to script
 E_WRONGARGS=66 # wrong number of arguments passed to script
-E_NOMATCH=67	# url not matched by regular expression
+E_NOMATCH=67   # url not matched by regular expression
 
 #+=========================================================+#
 # display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user				#
+# + or when invalid input is entered by the user            #
 #+=========================================================+#
 
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])"
 
 #+=========================================================+#
 # validate user input for first, second and third arguments #
-# + passed to script	by matching with regular expressions	#
+# + passed to script	by matching with regular expressions   #
 #+=========================================================+#
 
 first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
-second_arg_validated="^-t$"								# matches: -t
+second_arg_validated="^-t$"                        # matches: -t
 third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
 
 #+========================================================+#
-# second and third arguments passed to script are used	  #
-# + to specify a recording duration								  #
+# second and third arguments passed to script are used     #
+# + to specify a recording duration                        #
 #+========================================================+#
 
-tflag="$2" 		# second argument should be: -t
-duration="$3"	# third argument should be in this format: 00:00:00
+tflag="$2"     # second argument should be: -t
+duration="$3"  # third argument should be in this format: 00:00:00
 
 #+========================================================+#
-# check if first argument is a url in a text file 			  #
-# + or a url on the command line									  #
+# check if first argument is a url in a text file          #
+# + or a url on the command line                           #
 #+========================================================+#
 
 if [[ "$1" =~ \.txt$ ]]; then # - text file passed as first argument to script
-	videourl=$(cat "$1")  		# + cat the text file to extract the url
+	videourl=$(cat "$1")       # + cat the text file to extract the url
 else
-	videourl="$1"					# url is on the command line
+	videourl="$1"              # url is on the command line
 fi
 
 #+========================================================+#
-# check if 1 or 3 arguments are passed to script			  #
-# + and validate user input										  #
+# check if 1 or 3 arguments are passed to script           #
+# + and validate user input                                #
 #+========================================================+#
 
-if [[ $# -eq 1 ]]; then											# - one argument is passed to the script
+if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
 	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"			# + display invalid user input with error message
-		printf "%s\n" "$script_usage"							# + display script usage
-		exit "$E_NOMATCH"											# + exit with E_NOMATCH error code
+		printf "%s\n" "'$videourl' invalid input"       # + display invalid user input with error message
+		printf "%s\n" "$script_usage"                   # + display script usage
+		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
 	fi
-elif [[ $# -eq 3 ]]; then										# - three arguments are passed to the script, validate user input
+elif [[ $# -eq 3 ]]; then                             # - three arguments are passed to the script, validate user input
 	if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
-		printf "%s\n" "'$1 $2 $3' invalid input" 			# + display invalid user input with error message
-		printf "%s\n" "$script_usage"							# + display script usage
-		exit "$E_NOMATCH"											# + exit with E_NOMATCH error code
+		printf "%s\n" "'$1 $2 $3' invalid input"        # + display invalid user input with error message
+		printf "%s\n" "$script_usage"                   # + display script usage
+		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
 	fi
-else [[ $# -eq 0 ]]												# - no arguments are passed to the script
-   printf "%s\n" "$script_usage"								# + display script usage
-	exit "$E_NOARGS" 												# + exit with E_NOARGS error code
+else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
+   printf "%s\n" "$script_usage"                      # + display script usage
+	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
 fi
 
 #+========================================================+#
-# enable shell globbing for pattern matching					  #
+# enable shell globbing for pattern matching               #
 #+========================================================+#
 
 shopt -s extglob 
 
 #+========================================================+#
-# case statement switch on pattern match						  #
+# case statement switch on pattern match                   #
 #+========================================================+#
 
 videofile="@(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.@(mkv|mp4|avi|flv)"
@@ -98,7 +98,7 @@ rtmp="@(rtmp|rtmpe)://[a-zA-Z0-9[:blank:]#%@!()_=:-/.\&;,~*?]*"
 cookiem3u8uagent="@(http|https)://[a-zA-Z0-9:0-9./?=_,@\&%-]*\.m3u8\|[uU]ser-[aA]gent=[a-zA-Z0-9/.()[:blank:],:;%+_-]*\&Cookie=mediaAuth=[a-zA-Z0-9]*"
 
 #+========================================================+#
-# grep inside url to extract strings							  #
+# grep inside url to extract strings                       #
 #+========================================================+#
 
 videofile_grep=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.(mkv|mp4|avi|flv)')
@@ -111,8 +111,8 @@ cookieurl=$(printf "%s" "$videourl" | grep -Eo 'nltid=[a-zA-Z0-9&%_*=]*')
 cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*[^/]' | sed 's/^http\(\|s\):\/\///g')
 
 #+========================================================+#
-# case statement with regular expression 						  #
-# + to execute ffmpeg commands based on matching url		  #
+# case statement with regular expression                   #
+# + to execute ffmpeg commands based on matching url       #
 #+========================================================+#
 
 case "$videourl" in
@@ -204,7 +204,7 @@ case "$videourl" in
 		printf "%s\n" "Streaming: a'$videourl'"
 		ffmpeg -hide_banner -i "$videourl" -c:v copy -c:a copy $tflag $duration \
 		-f mpegts udp://239.253.253.4:1234?pkt_size=1316;;
-	*) 		           # wildcard
+	*)                  # wildcard
 		printf "%s\n" 'url matches: * bash pattern'
 		printf "%s\n" "Streaming: '$videourl'"
 		ffmpeg -hide_banner -re -i "$videourl" \
@@ -217,13 +217,13 @@ case "$videourl" in
 esac 
 
 #+========================================================+#
-# turn off shell globbing											  #
+# turn off shell globbing                                  #
 #+========================================================+#
 
 shopt -u extglob 
 
 #+========================================================+#
-# exit status SUCCESS if script runs without errors		  #
+# exit status SUCCESS if script runs without errors        #
 #+========================================================+#
 
 exit "$SUCCESS"
