bash

diff --git a/bash-scripts/rip-record b/bash-scripts/rip-record
--- a/bash-scripts/rip-record
+++ b/bash-scripts/rip-record
@@ -1,27 +1,46 @@
 #!/bin/bash
 
-# rip-record - execute ffmpeg commands based on matching url #
+# rip-record - execute ffmpeg commands based on matching url
+#===========================================================
 
 # exit status
 SUCCESS=0
 E_NOARGS=65
 
 # script usage
-script_usage="Usage: $(basename $0) [video url] {[-t] [00:00:00]}"
+script_usage="Usage: $(basename $0) [video url] ([-t] [00:00:00])"
 
-# validate user input for first, second, third arguments passed to script
+# validate user input for 1st, 2nd and 3rd arguments passed to script
 first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
 second_arg_validated="^-t$"								# matches: -t
 third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
 
-# ffmpeg duration second and third arguments passed to script
+# ffmpeg duration - 2nd and 3rd arguments passed to script
 tflag="$2"
 duration="$3" 
 
 # check if 1 or 3 arguments are passed to script
-[[ $# -eq 1 ]] || [[ $# -eq 3 ]] || exit "$E_NOARGS"  
+
+#[[ $# -eq 1 ]] || [[ $# -eq 3 ]] || exit "$E_NOARGS"  
 
 [[ "$1" =~ \.txt$ ]] && videourl=$(cat "$1") || videourl="$1"
+
+
+if [[ $# -eq 1 ]]; then
+	if ! [[ $videourl =~ $first_arg_validated ]]; then
+		printf "%s\n" "'$videourl' invalid input"
+	   printf "%s\n" "$script_usage"
+		exit "$E_NOARGS" 
+	fi
+elif [[ $# -eq 3 ]]; then
+	echo "3 args"
+else
+   printf "%s\n" "$script_usage"
+	exit "$E_NOARGS" 
+fi
+
+#[[ $videourl =~ $first_arg_validated ]] || \
+#printf "%s\n" "'$videourl' invalid input"; printf "%s\n" "$script_usage" && exit "$E_NOARGS" 
 
 # first arg check
 #if ! [[ $videourl =~ $first_arg_validated ]]; then
