rip-record comment style

diff --git a/bash-scripts/rip-record b/bash-scripts/rip-record
--- a/bash-scripts/rip-record
+++ b/bash-scripts/rip-record
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #+=========================================================+#
-# exit status and error codes                               #
+# exit status, error codes and script usage                 #
 #+=========================================================+#
 
 SUCCESS=0      # success exit code
@@ -9,26 +9,18 @@ E_NOARGS=65    # no arguments passed to script
 E_WRONGARGS=66 # wrong number of arguments passed to script
 E_NOMATCH=67   # url not matched by regular expression
 
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
-
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])"
 
 #+=========================================================+#
 # validate user input for first, second and third arguments #
 # + passed to script	by matching with regular expressions   #
+# second and third arguments passed to script are used      #
+# + to specify a recording duration                         #
 #+=========================================================+#
 
 first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
 second_arg_validated="^-t$"                        # matches: -t
 third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
-
-#+========================================================+#
-# second and third arguments passed to script are used     #
-# + to specify a recording duration                        #
-#+========================================================+#
 
 tflag="$2"     # second argument should be: -t
 duration="$3"  # third argument should be in this format: 00:00:00
@@ -46,19 +38,17 @@ fi
 
 #+========================================================+#
 # check if 1 or 3 arguments are passed to script           #
-# + and validate user input                                #
+# + validate user input and enable shell globing           #
 #+========================================================+#
 
 if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
 	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"       # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
+		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # + display invalid user input with error message
 		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
 	fi
 elif [[ $# -eq 3 ]]; then                             # - three arguments are passed to the script, validate user input
 	if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
-		printf "%s\n" "'$1 $2 $3' invalid input"        # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
+		printf "%s\n%s\n" "'$1 $2 $3' invalid input" "$script_usage" # + display invalid user input with error message
 		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
 	fi
 else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
@@ -66,11 +56,7 @@ else [[ $# -eq 0 ]]                                   # - no arguments are passe
 	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
 fi
 
-#+========================================================+#
-# enable shell globbing for pattern matching               #
-#+========================================================+#
-
-shopt -s extglob 
+shopt -s extglob # enable shell globbing 
 
 #+========================================================+#
 # case statement switch on pattern match                   #
@@ -106,7 +92,6 @@ cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*
 # recording functions using ffmpeg and rtmpdump           +#
 #+========================================================+#
 
-# ffmpeg function
 record () {
 printf "%s\n" "Recording: '$videourl'"
 count=0 # set count to zero
@@ -123,7 +108,6 @@ sleep 1
 done
 }
 
-# rtmpdump function
 record_rtmp () {
 printf "%s\n" "Recording: '$videourl'"
 count=0 # set count to zero
@@ -146,44 +130,22 @@ done
 #+========================================================+#
 
 case "$videourl" in
-  $videofile)         # video file
-       record "$videourl";;
-  $m3u8)              # m3u8 playlist
-       record "$videourl";;
-  $cookiem3u8)        # cookie m3u8
-       record "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
-  $videoqmark)         # video link and question mark
-       record "$videourl";;
-  $xforward)          # xforward
-       record "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
-  $useref)            # useragent referer
-       record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
-  $viduseragent)     # user agent 
-       record "$videofile_grep" -user-agent "$useragent";;
-  $useragentreferer) # useragent referer
-       record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
-  $refuseragent)      # referer user agent
-       record "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
-  $rtmp)              # rtmp
-       record_rtmp "$videourl";;
-  $cookiem3u8uagent)  # cookie m3u8 useragent
-       record "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
-  $http)              # http
-       record "$videourl";;
-  *)                  # wildcard
-       record "$videourl";;
+  $videofile) record "$videourl";;
+  $m3u8) record "$videourl";;
+  $cookiem3u8) record "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
+  $videoqmark) record "$videourl";;
+  $xforward) record "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
+  $useref) record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
+  $viduseragent) record "$videofile_grep" -user-agent "$useragent";;
+  $useragentreferer) record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
+  $refuseragent) record "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
+  $rtmp) record_rtmp "$videourl";;
+  $cookiem3u8uagent) record "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
+  $http) record "$videourl";;
+  *) record "$videourl";;
 esac \
 && type -P notify-send &> /dev/null && [[ $? -eq 0 ]] \
 && notify-send -i kodi "Finished Recording" "$videourl"
 
-#+========================================================+#
-# turn off shell globbing                                  #
-#+========================================================+#
-
-shopt -u extglob 
-
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+shopt -u extglob # turn off shell globbing
+exit "$SUCCESS" # exit status SUCCESS if script runs without errors
