rip-record

diff --git a/bash-scripts/rip-record b/bash-scripts/rip-record
--- a/bash-scripts/rip-record
+++ b/bash-scripts/rip-record
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-#+=========================================================+#
-# exit status, error codes and script usage                 #
-#+=========================================================+#
+#+========================================================+#
+# exit status, error codes and script usage                #
+#+========================================================+#
 
 SUCCESS=0      # success exit code
 E_NOARGS=65    # no arguments passed to script
@@ -11,20 +11,19 @@ E_NOMATCH=67   # url not matched by regular expression
 
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])"
 
-#+=========================================================+#
-# validate user input for first, second and third arguments #
-# + passed to script	by matching with regular expressions   #
-# second and third arguments passed to script are used      #
-# + to specify a recording duration                         #
-#+=========================================================+#
-
 #+========================================================+#
-# check if first argument is a url in a text file          #
-# + or a url on the command line                           #
+# + check if first argument is a url in a text file        #
+# - or a url on the command line                           #
+# + validate user input for first, second, third arguments #
+# - passed to script	by matching with regular expressions  #
+# + second and third arguments passed to script are used   #
+# - to specify a recording duration                        #
+# + check if 1 or 3 arguments are passed to script         #
+# - validate user input and enable shell globing           #
 #+========================================================+#
 
-if [[ "$1" =~ \.txt$ ]]; then # - text file passed as first argument to script
-	videourl=$(cat "$1")       # + cat the text file to extract the url
+if [[ "$1" =~ \.txt$ ]]; then # + text file passed as first argument to script
+	videourl=$(cat "$1")       # - cat the text file to extract the url
 else
 	videourl="$1"              # url is on the command line
 fi
@@ -36,24 +35,19 @@ third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
 tflag="$2"     # second argument should be: -t
 duration="$3"  # third argument should be in this format: 00:00:00
 
-#+========================================================+#
-# check if 1 or 3 arguments are passed to script           #
-# + validate user input and enable shell globing           #
-#+========================================================+#
-
-if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # + display invalid user input with error message
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+if [[ $# -eq 1 ]]; then                               # + one argument is passed to the script
+	if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
+		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-elif [[ $# -eq 3 ]]; then                             # - three arguments are passed to the script, validate user input
+elif [[ $# -eq 3 ]]; then                             # + three arguments are passed to the script, validate user input
 	if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
 		printf "%s\n%s\n" "'$1 $2 $3' invalid input" "$script_usage" # + display invalid user input with error message
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
-   printf "%s\n" "$script_usage"                      # + display script usage
-	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
+else [[ $# -eq 0 ]]                                   # + no arguments are passed to the script
+   printf "%s\n" "$script_usage"                      # - display script usage
+	exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
 fi
 
 shopt -s extglob # enable shell globbing 
@@ -125,8 +119,8 @@ done
 }
 
 #+========================================================+#
-# case statement with regular expression                   #
-# + to execute ffmpeg commands based on matching url       #
+# + case statement with regular expression                 #
+# - to execute ffmpeg commands based on matching url       #
 #+========================================================+#
 
 case "$videourl" in
