rip ssh

diff --git a/bash-scripts/rip-ssh b/bash-scripts/rip-ssh
--- a/bash-scripts/rip-ssh
+++ b/bash-scripts/rip-ssh
@@ -1,11 +1,11 @@
 #!/bin/bash
 
 #+==========================================================+#
-# rip-record - execute ffmpeg commands based on matching url #
+# rip-ssh - execute ffmpeg commands based on matching url    #
 #+==========================================================+#
 
 # diagram of how the script works
-# [rip-record] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [ffmpeg]
+# [rip-ssh] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [ssh]
 
 #+=========================================================+#
 # exit status and error codes											#
@@ -28,48 +28,49 @@ script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/vid
 # + passed to script	by matching with regular expressions	#
 #+=========================================================+#
 
-first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
-second_arg_validated="^-t$"								# matches: -t
-third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
+sshserver="$1"
+second_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
+third_arg_validated="^-t$"								# matches: -t
+fourth_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
 
 #+========================================================+#
 # second and third arguments passed to script are used	  #
 # + to specify a recording duration								  #
 #+========================================================+#
 
-tflag="$2" 		# second argument should be: -t
-duration="$3"	# third argument should be in this format: 00:00:00
+tflag="$3" 		# third argument should be: -t
+duration="$4"	# fourth argument should be in this format: 00:00:00
 
 #+========================================================+#
-# check if first argument is a url in a text file 			  #
+# check if second argument is a url in a text file 		  #
 # + or a url on the command line									  #
 #+========================================================+#
 
-if [[ "$1" =~ \.txt$ ]]; then # - text file passed as first argument to script
-	videourl=$(cat "$1")  		# + cat the text file to extract the url
+if [[ "$2" =~ \.txt$ ]]; then # - text file passed as second argument to script
+	videourl=$(cat "$2")  		# + cat the text file to extract the url
 else
-	videourl="$1"					# url is on the command line
+	videourl="$2"					# url is on the command line
 fi
 
 #+========================================================+#
-# check if 1 or 3 arguments are passed to script			  #
+# check if 2 or 4 arguments are passed to script			  #
 # + and validate user input										  #
 #+========================================================+#
 
-if [[ $# -eq 1 ]]; then											# - one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"			# + display invalid user input with error message
-		printf "%s\n" "$script_usage"							# + display script usage
-		exit "$E_NOMATCH"											# + exit with E_NOMATCH error code
+if [[ $# -eq 2 ]]; then										    # - two argument are passed to the script
+	if ! [[ $videourl =~ $second_arg_validated ]]; then # + if videourl doesnt match validation regular expression
+		printf "%s\n" "'$videourl' invalid input"			 # + display invalid user input with error message
+		printf "%s\n" "$script_usage"							 # + display script usage
+		exit "$E_NOMATCH"											 # + exit with E_NOMATCH error code
 	fi
-elif [[ $# -eq 3 ]]; then										# - three arguments are passed to the script, validate user input
-	if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
-		printf "%s\n" "'$1 $2 $3' invalid input" 			# + display invalid user input with error message
-		printf "%s\n" "$script_usage"							# + display script usage
-		exit "$E_NOMATCH"											# + exit with E_NOMATCH error code
+elif [[ $# -eq 4 ]]; then										 # - three arguments are passed to the script, validate user input
+	if ! [[ $videourl =~ $second_arg_validated && $tflag =~ $third_arg_validated && $duration =~ $fourth_arg_validated ]]; then
+		printf "%s\n" "'$1 $2 $3 $4' invalid input" 		 # + display invalid user input with error message
+		printf "%s\n" "$script_usage"							 # + display script usage
+		exit "$E_NOMATCH"											 # + exit with E_NOMATCH error code
 	fi
-else [[ $# -eq 0 ]]												# - no arguments are passed to the script
-   printf "%s\n" "$script_usage"								# + display script usage
+else [[ $# -eq 0 ]]												 # - no arguments are passed to the script
+   printf "%s\n" "$script_usage"								 # + display script usage
 	exit "$E_NOARGS" 												# + exit with E_NOARGS error code
 fi
 
