rip-record-reconnect comment style

diff --git a/bash-scripts/rip-record-reconnect b/bash-scripts/rip-record-reconnect
--- a/bash-scripts/rip-record-reconnect
+++ b/bash-scripts/rip-record-reconnect
@@ -1,14 +1,7 @@
 #!/bin/bash
 
-#+====================================================================+#
-# rip-record-reconnect - execute ffmpeg commands based on matching url #
-#+====================================================================+#
-
-# diagram of how the script works
-# [rip-record-reconnect] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [ffmpeg]
-
 #+=========================================================+#
-# exit status and error codes                               #
+# exit status, error codes and script usage                 #
 #+=========================================================+#
 
 SUCCESS=0      # success exit code
@@ -16,26 +9,18 @@ E_NOARGS=65    # no arguments passed to script
 E_WRONGARGS=66 # wrong number of arguments passed to script
 E_NOMATCH=67   # url not matched by regular expression
 
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
-
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])"
 
 #+=========================================================+#
 # validate user input for first, second and third arguments #
 # + passed to script	by matching with regular expressions   #
+# second and third arguments passed to script are used      #
+# + to specify a recording duration                         #
 #+=========================================================+#
 
 first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
 second_arg_validated="^-t$"                        # matches: -t
 third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
-
-#+========================================================+#
-# second and third arguments passed to script are used     #
-# + to specify a recording duration                        #
-#+========================================================+#
 
 tflag="$2"     # second argument should be: -t
 duration="$3"  # third argument should be in this format: 00:00:00
@@ -53,7 +38,7 @@ fi
 
 #+========================================================+#
 # check if 1 or 3 arguments are passed to script           #
-# + and validate user input                                #
+# + validate user input and enable shell globing           #
 #+========================================================+#
 
 if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
@@ -73,11 +58,7 @@ else [[ $# -eq 0 ]]                                   # - no arguments are passe
 	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
 fi
 
-#+========================================================+#
-# enable shell globbing for pattern matching               #
-#+========================================================+#
-
-shopt -s extglob 
+shopt -s extglob # enable shell globbing 
 
 #+========================================================+#
 # case statement switch on pattern match                   #
@@ -113,7 +94,6 @@ cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*
 # recording functions using ffmpeg and rtmpdump           +#
 #+========================================================+#
 
-# ffmpeg function
 record () {
 printf "%s\n" "Recording: '$videourl'"
 count=0 # set count to zero
@@ -131,7 +111,6 @@ sleep 1
 done
 }
 
-# rtmpdump function
 record_rtmp () {
 printf "%s\n" "Recording: '$videourl'"
 count=0 # set count to zero
@@ -154,57 +133,22 @@ done
 #+========================================================+#
 
 case "$videourl" in
-  $videofile)         # video file
-       printf "%s\n" 'url matches: $videofile bash pattern'
-       record "$videourl";;
-  $m3u8)              # m3u8 playlist
-       printf "%s\n" 'url matches: $m3u8 bash pattern'
-       record "$videourl";;
-  $cookiem3u8)        # cookie m3u8
-       printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
-       record "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
-  $videoqmark)         # video link and question mark
-       printf "%s\n" 'url matches: $videoqmark bash pattern'
-       record "$videourl";;
-  $xforward)          # xforward
-       printf "%s\n" 'url matches: $xforward bash pattern'
-       record "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
-  $useref)            # useragent referer
-       printf "%s\n" 'url matches: $useref bash pattern'
-       record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
-  $viduseragent)     # user agent 
-       printf "%s\n" 'url matches: $viduseragent bash pattern'
-       record "$videofile_grep" -user-agent "$useragent";;
-  $useragentreferer) # useragent referer
-       printf "%s\n" 'url matches: $useragentreferer bash pattern'
-       record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
-  $refuseragent)      # referer user agent
-       printf "%s\n" 'url matches: $refuseragent bash pattern'
-       record "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
-  $rtmp)              # rtmp
-       printf "%s\n" 'url matches: $rtmp bash pattern'
-       record_rtmp "$videourl";;
-  $cookiem3u8uagent)  # cookie m3u8 useragent
-       printf "%s\n" 'url matches: $cookiem3u8uagent bash pattern'
-       record "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
-  $http)              # http
-       printf "%s\n" 'url matches: $http bash pattern'
-       record "$videourl";;
-  *)                  # wildcard
-       printf "%s\n" 'url matches: * bash pattern'
-       record "$videourl";;
+  $videofile) record "$videourl";;
+  $m3u8) record "$videourl";;
+  $cookiem3u8) record "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
+  $videoqmark) record "$videourl";;
+  $xforward) record "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
+  $useref) record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
+  $viduseragent) record "$videofile_grep" -user-agent "$useragent";;
+  $useragentreferer) record "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
+  $refuseragent) record "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
+  $rtmp) record_rtmp "$videourl";;
+  $cookiem3u8uagent) record "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
+  $http) record "$videourl";;
+  *) record "$videourl";;
 esac \
 && type -P notify-send &> /dev/null && [[ $? -eq 0 ]] \
 && notify-send -i kodi "Finished Recording" "$videourl"
 
-#+========================================================+#
-# turn off shell globbing                                  #
-#+========================================================+#
-
-shopt -u extglob 
-
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+shopt -u extglob # turn off shell globbing
+exit "$SUCCESS" # exit status SUCCESS if script runs without errors
