rip-ssh comment style

diff --git a/bash-scripts/rip-ssh b/bash-scripts/rip-ssh
--- a/bash-scripts/rip-ssh
+++ b/bash-scripts/rip-ssh
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #+=========================================================+#
-# exit status and error codes                               #
+# exit status, error codes and script usage                 #
 #+=========================================================+#
 
 SUCCESS=0      # success exit code
@@ -9,16 +9,13 @@ E_NOARGS=65    # no arguments passed to script
 E_WRONGARGS=66 # wrong number of arguments passed to script
 E_NOMATCH=67   # url not matched by regular expression
 
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
-
 script_usage="Usage: $(basename "$0") [ssh server] [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])"
 
 #+=========================================================+#
 # validate user input for first, second and third arguments #
 # + passed to script	by matching with regular expressions   #
+# third and fourth arguments passed to script are used      #
+# + to specify a recording duration                         #
 #+=========================================================+#
 
 sshserver="$1"                                      # ssh server
@@ -26,11 +23,6 @@ first_arg_validated="^[a-zA-Z0-9:0-9./@-]*"         # validate ssh server addres
 second_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
 third_arg_validated="^-t$"                          # matches: -t
 fourth_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
-
-#+========================================================+#
-# second and third arguments passed to script are used     #
-# + to specify a recording duration                        #
-#+========================================================+#
 
 tflag="$3"     # third argument should be: -t
 duration="$4"  # fourth argument should be in this format: 00:00:00
@@ -48,19 +40,17 @@ fi
 
 #+========================================================+#
 # check if 2 or 4 arguments are passed to script           #
-# + and validate user input                                #
+# + validate user input and enable shell globing           #
 #+========================================================+#
 
 if [[ $# -eq 2 ]]; then                                # - two argument are passed to the script
 	if ! [[ $videourl =~ $second_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"        # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                    # + display script usage
+		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # + display invalid user input with error message
 		exit "$E_NOMATCH"                                # + exit with E_NOMATCH error code
 	fi
 elif [[ $# -eq 4 ]]; then                              # - three arguments are passed to the script, validate user input
 	if ! [[ $sshserver =~ $first_arg_validated && $videourl =~ $second_arg_validated && $tflag =~ $third_arg_validated && $duration =~ $fourth_arg_validated ]]; then
-		printf "%s\n" "'$1 $2 $3 $4' invalid input"      # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                    # + display script usage
+		printf "%s\n%s\n" "'$1 $2 $3 $4' invalid input" "$script_usage" # + display invalid user input with error message
 		exit "$E_NOMATCH"                                # + exit with E_NOMATCH error code
 	fi
 else [[ $# -eq 0 ]]                                    # - no arguments are passed to the script
@@ -68,17 +58,7 @@ else [[ $# -eq 0 ]]                                    # - no arguments are pass
 	exit "$E_NOARGS"                                    # + exit with E_NOARGS error code
 fi
 
-#+========================================================+#
-# enable shell globbing for pattern matching               #
-#+========================================================+#
-
-shopt -s extglob 
-
-#+========================================================+#
-# video recording file path                                #
-#+========================================================+#
-
-recordingfile="$HOME/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
+shopt -s extglob # enable shell globbing 
 
 #+========================================================+#
 # case statement switch on pattern match                   #
@@ -114,7 +94,8 @@ cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*
 # recording functions using ffmpeg and rtmpdump           +#
 #+========================================================+#
 
-# ffmpeg function
+recordingfile="$HOME/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
+
 record_ssh () {
 printf "%s %s %s %s %s %s %s %s %s %s %s\n" \
 'ffmpeg -hide_banner -loglevel error' $2 $3 $4 $5 '-i' "$1" \
@@ -230,14 +211,5 @@ case "$videourl" in
 		| ssh -fn "$sshserver" $(< /dev/fd/0) &>/dev/null;;
 esac 
 
-#+========================================================+#
-# turn off shell globbing                                  #
-#+========================================================+#
-
-shopt -u extglob 
-
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+shopt -u extglob # turn off shell globbing
+exit "$SUCCESS" # exit status SUCCESS if script runs without errors
