rip-stream

diff --git a/bash-scripts/rip-stream b/bash-scripts/rip-stream
--- a/bash-scripts/rip-stream
+++ b/bash-scripts/rip-stream
@@ -1,83 +1,56 @@
 #!/bin/bash
 
-#+==========================================================+#
-# rip-stream - execute ffmpeg commands based on matching url #
-#+==========================================================+#
-
-# diagram of how the script works
-# [rip-stream] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [ffmpeg]
-
-#+=========================================================+#
-# exit status and error codes                               #
-#+=========================================================+#
+#+========================================================+#
+# exit status, error codes and script usage                #
+#+========================================================+#
 
 SUCCESS=0      # success exit code
 E_NOARGS=65    # no arguments passed to script
 E_WRONGARGS=66 # wrong number of arguments passed to script
 E_NOMATCH=67   # url not matched by regular expression
 
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
-
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])"
 
-#+=========================================================+#
-# validate user input for first, second and third arguments #
-# + passed to script	by matching with regular expressions   #
-#+=========================================================+#
+#+========================================================+#
+# + check if first argument is a url in a text file        #
+# - or a url on the command line                           #
+# + validate user input for first, second, third arguments #
+# - passed to script	by matching with regular expressions  #
+# + second and third arguments passed to script are used   #
+# - to specify a recording duration                        #
+# + check if 1 or 3 arguments are passed to script         #
+# - validate user input and enable shell globing           #
+#+========================================================+#
+
+if [[ "$1" =~ \.txt$ ]]; then # + text file passed as first argument to script
+	videourl=$(cat "$1")       # - cat the text file to extract the url
+else
+	videourl="$1"              # url is on the command line
+fi
 
 first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
 second_arg_validated="^-t$"                        # matches: -t
 third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
 
-#+========================================================+#
-# second and third arguments passed to script are used     #
-# + to specify a recording duration                        #
-#+========================================================+#
-
 tflag="$2"     # second argument should be: -t
 duration="$3"  # third argument should be in this format: 00:00:00
 
-#+========================================================+#
-# check if first argument is a url in a text file          #
-# + or a url on the command line                           #
-#+========================================================+#
-
-if [[ "$1" =~ \.txt$ ]]; then # - text file passed as first argument to script
-	videourl=$(cat "$1")       # + cat the text file to extract the url
-else
-	videourl="$1"              # url is on the command line
-fi
-
-#+========================================================+#
-# check if 1 or 3 arguments are passed to script           #
-# + and validate user input                                #
-#+========================================================+#
-
-if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"       # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+if [[ $# -eq 1 ]]; then                               # + one argument is passed to the script
+	if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
+		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-elif [[ $# -eq 3 ]]; then                             # - three arguments are passed to the script, validate user input
+elif [[ $# -eq 3 ]]; then                             # + three arguments are passed to the script, validate user input
 	if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
-		printf "%s\n" "'$1 $2 $3' invalid input"        # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+		printf "%s\n%s\n" "'$1 $2 $3' invalid input" "$script_usage" # - display invalid user input with error message
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
-   printf "%s\n" "$script_usage"                      # + display script usage
-	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
+else [[ $# -eq 0 ]]                                   # + no arguments are passed to the script
+   printf "%s\n" "$script_usage"                      # - display script usage
+	exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
 fi
 
-#+========================================================+#
-# enable shell globbing for pattern matching               #
-#+========================================================+#
-
-shopt -s extglob 
+shopt -s extglob # enable shell globbing 
 
 #+========================================================+#
 # case statement switch on pattern match                   #
@@ -113,9 +86,7 @@ cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*
 # streaming functions using ffmpeg and rtmpdump           +#
 #+========================================================+#
 
-# ffmpeg function
 stream () {
-printf "%s\n" "Streaming: '$videourl'"
 ffmpeg -hide_banner -loglevel error $2 $3 $4 $5 -i "$1" \
 -c:v libx265 -preset ultrafast -tune zero-latency \
 -x265-params crf=28 \
@@ -125,9 +96,7 @@ $tflag $duration \
 -f mpegts udp://239.253.253.4:1234?pkt_size=1316
 }
 
-# rtmpdump function
 stream_rtmp () {
-printf "%s\n" "Streaming: '$videourl'"
 rtmpdump -q -i "$1" | ffmpeg -hide_banner -i - \
 -c:v libx265 -preset ultrafast -tune zero-latency \
 -x265-params crf=28 \
@@ -136,60 +105,27 @@ rtmpdump -q -i "$1" | ffmpeg -hide_banner -i - \
 }
 
 #+========================================================+#
-# case statement with regular expression                   #
-# + to execute ffmpeg commands based on matching url       #
+# + case statement with regular expression                 #
+# - to execute ffmpeg commands based on matching url       #
 #+========================================================+#
+
+printf "%s\n" "Streaming: '$videourl'"
 
 case "$videourl" in
-	$videofile)         # video file
-      printf "%s\n" 'url matches: $videofile bash pattern'
-      stream "$videourl";;
-	$m3u8)              # m3u8 playlist
-      printf "%s\n" 'url matches: $m3u8 bash pattern'
-      stream "$videourl";;
-	$cookiem3u8)        # cookie m3u8
-      printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
-      stream "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
-	$videoqmark)         # video link and question mark
-      printf "%s\n" 'url matches: $videoqmark bash pattern'
-      stream "$videourl";;
-	$xforward)          # xforward
-      printf "%s\n" 'url matches: $xforward bash pattern'
-      stream "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
-	$useref)            # useragent referer
-      printf "%s\n" 'url matches: $useref bash pattern'
-      stream "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
-	$viduseragent)     # user agent 
-      printf "%s\n" 'url matches: $viduseragent bash pattern'
-      stream "$videofile_grep" -user-agent "$useragent";;
-	$useragentreferer) # useragent referer
-      printf "%s\n" 'url matches: $useragentreferer bash pattern'
-      stream "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
-	$refuseragent)      # referer user agent
-      printf "%s\n" 'url matches: $refuseragent bash pattern'
-      stream "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
-	$rtmp)              # rtmp
-      printf "%s\n" 'url matches: $rtmp bash pattern'
-      stream_rtmp "$videourl";;
-	$cookiem3u8uagent)  # cookie m3u8 useragent
-      printf "%s\n" 'url matches: $cookiem3u8uagent bash pattern'
-      stream "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
-	$http)              # http
-      printf "%s\n" 'url matches: $http bash pattern'
-      stream "$videourl";;
-	*)                  # wildcard
-      printf "%s\n" 'url matches: * bash pattern'
-      stream "$videourl";;
+	$videofile) stream "$videourl";;
+	$m3u8) stream "$videourl";;
+	$cookiem3u8) stream "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
+	$videoqmark) stream "$videourl";;
+	$xforward) stream "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
+	$useref) stream "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
+	$viduseragent) stream "$videofile_grep" -user-agent "$useragent";;
+	$useragentreferer) stream "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
+	$refuseragent) stream "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
+	$rtmp) stream_rtmp "$videourl";;
+	$cookiem3u8uagent) stream "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
+	$http) stream "$videourl";;
+	*) stream "$videourl";;
 esac 
 
-#+========================================================+#
-# turn off shell globbing                                  #
-#+========================================================+#
-
-shopt -u extglob 
-
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+shopt -u extglob # turn off shell globbing
+exit "$SUCCESS" # exit status SUCCESS if script runs without errors
