rip-ytdl youtube and aria2c

diff --git a/bash-scripts/rip-ytdl b/bash-scripts/rip-ytdl
--- a/bash-scripts/rip-ytdl
+++ b/bash-scripts/rip-ytdl
@@ -34,11 +34,11 @@ videourl_validated="^(http|https)://*" # matches: http|https
 #+========================================================+#
 
 if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
-	if ! [[ "$1" =~ $videourl_validated || -d "$1" || -f "$1" ]]; then # + validate user input
-		printf "%s\n" "'$1' invalid input"              # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
-	fi
+   if ! [[ "$1" =~ $videourl_validated || -d "$1" || -f "$1" ]]; then # + validate user input
+      printf "%s\n" "'$1' invalid input"              # + display invalid user input with error message
+      printf "%s\n" "$script_usage"                   # + display script usage
+      exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+   fi
 else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
    printf "%s\n" "$script_usage"                      # + display script usage
 	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
