rip-stats

diff --git a/bash-scripts/rip-stats b/bash-scripts/rip-stats
--- a/bash-scripts/rip-stats
+++ b/bash-scripts/rip-stats
@@ -1,72 +1,43 @@
 #!/bin/bash
 
-#+==========================================================+#
-# rip-stats - execute ffprobe commands based on matching url #
-#+==========================================================+#
-
-# diagram of how the script works
-# [rip-stats] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [ffprobe]
-
-#+=========================================================+#
-# exit status and error codes                               #
-#+=========================================================+#
+#+========================================================+#
+# exit status, error codes and script usage                #
+#+========================================================+#
 
 SUCCESS=0      # success exit code
 E_NOARGS=65    # no arguments passed to script
 E_NOMATCH=66   # url not matched by regular expression
 
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
-
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url]"
 
-#+=========================================================+#
-# validate user input for first argument                    #
-# + passed to script	by matching with regular expressions   #
-#+=========================================================+#
-
-first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
-
 #+========================================================+#
-# check if first argument is a url in a text file          #
-# + or a url on the command line                           #
+# + check if first argument is a url in a text file        #
+# - or a url on the command line                           #
+# + validate user input for first argument                 #
+# - passed to script	by matching with regular expressions  #
+# + check if 1 argument is passed to script                #
+# - validate user input and enable shell globing           #
 #+========================================================+#
 
-if [[ "$1" =~ \.txt$ ]]; then # - text file passed as first argument to script
-	videourl=$(cat "$1")       # + cat the text file to extract the url
+if [[ "$1" =~ \.txt$ ]]; then # + text file passed as first argument to script
+	videourl=$(cat "$1")       # - cat the text file to extract the url
 else
 	videourl="$1"              # url is on the command line
 fi
 
-#+========================================================+#
-# check if 1 argument is  passed to script                 #
-# + and validate user input                                #
-#+========================================================+#
+first_arg_validated="^(http|https|rtmp|rtmpe)://*"    # matches: http|https|rtmp|rtmpe
 
-if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"       # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+if [[ $# -eq 1 ]]; then                               # + one argument is passed to the script
+	if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
+		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
-   printf "%s\n" "$script_usage"                      # + display script usage
-	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
+else [[ $# -eq 0 ]]                                   # + no arguments are passed to the script
+   printf "%s\n" "$script_usage"                      # - display script usage
+	exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
 fi
 
-#+========================================================+#
-# enable shell globbing for pattern matching               #
-#+========================================================+#
-
-shopt -s extglob 
-
-#+========================================================+#
-# video recording file path                                #
-#+========================================================+#
-
-statistics_file="$HOME/Desktop/video-stats-$(date +"%Y-%m-%d-%H-%M-%S").txt" 
+shopt -s extglob # enable shell globbing 
 
 #+========================================================+#
 # case statement switch on pattern match                   #
@@ -102,7 +73,8 @@ cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*
 # ffrobe bash functions                                   +#
 #+========================================================+#
 
-# ffprobe function
+statistics_file="$HOME/Desktop/video-stats-$(date +"%Y-%m-%d-%H-%M-%S").txt" 
+
 stats () {
 printf "%s\n" "Statistics for: '$videourl'"
 ffprobe -v error -hide_banner -pretty -show_entries \
@@ -111,7 +83,6 @@ $2 $3 $4 $5 -i "$1" \
 | tee "$statistics_file"
 }
 
-# rtmpdump function
 stats_rtmp () {
 printf "%s\n" "Statistics for: '$videourl'"
 printf "%s\n" "Statistics for: '$videourl'"
@@ -122,60 +93,25 @@ format=size,duration:stream=filename,index,codec_type,codec_name,profile,bit_rat
 }
 
 #+========================================================+#
-# case statement with regular expression                   #
-# + to execute ffprobe commands based on matching url      #
+# + case statement with regular expression                 #
+# - to execute ffprobe commands based on matching url      #
 #+========================================================+#
 
 case "$videourl" in
-	$videofile)         # video file
-      printf "%s\n" 'url matches: $videofile bash pattern'
-      stats "$videourl";;
-	$m3u8)              # m3u8 playlist
-      printf "%s\n" 'url matches: $m3u8 bash pattern'
-      stats "$videourl";;
-	$cookiem3u8)        # cookie m3u8
-      printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
-      stats "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
-	$videoqmark)         # video link and question mark
-      printf "%s\n" 'url matches: $videoqmark bash pattern'
-      stats "$videourl";;
-	$xforward)          # xforward
-      printf "%s\n" 'url matches: $xforward bash pattern'
-      stats "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
-	$useref)            # useragent referer
-      printf "%s\n" 'url matches: $useref bash pattern'
-      stats "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
-	$viduseragent)     # user agent 
-      printf "%s\n" 'url matches: $viduseragent bash pattern'
-      stats "$videofile_grep" -user-agent "$useragent";;
-	$useragentreferer) # useragent referer
-      printf "%s\n" 'url matches: $useragentreferer bash pattern'
-      stats "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
-	$refuseragent)      # referer user agent
-      printf "%s\n" 'url matches: $refuseragent bash pattern'
-      stats "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
-	$rtmp)              # rtmp
-      printf "%s\n" 'url matches: $rtmp bash pattern'
-      stats_rtmp "$videourl";;
-	$cookiem3u8uagent)  # cookie m3u8 useragent
-      printf "%s\n" 'url matches: $cookiem3u8uagent bash pattern'
-      stats "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
-	$http)              # http
-      printf "%s\n" 'url matches: $http bash pattern'
-      stats "$videourl";;
-	*)                  # wildcard
-      printf "%s\n" 'url matches: * bash pattern'
-      stats "$videourl";;
+	$videofile) stats "$videourl";;
+	$m3u8) stats "$videourl";;
+	$cookiem3u8) stats "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
+	$videoqmark) stats "$videourl";;
+	$xforward) stats "$videofile_grep" -headers "'X-Forwarded-For: '"$xforwardip"''$'\r\n'";;
+	$useref) stats "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
+	$viduseragent) stats "$videofile_grep" -user-agent "$useragent";;
+	$useragentreferer) stats "$videofile_grep" -user-agent "$useragent" -headers "'Referer: '"$referer"''$'\r\n'";;
+	$refuseragent) stats "$videofile_grep" -headers "'Referer: '"$referer"''$'\r\n'" -user-agent "$useragent";;
+	$rtmp) stats_rtmp "$videourl";;
+	$cookiem3u8uagent) stats "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
+	$http) stats "$videourl";;
+	*) stats "$videourl";;
 esac 
 
-#+========================================================+#
-# turn off shell globbing                                  #
-#+========================================================+#
-
-shopt -u extglob 
-
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+shopt -u extglob # turn off shell globbing
+exit "$SUCCESS" # exit status SUCCESS if script runs without errors
