rip-record-reconnect

diff --git a/bash-scripts/rip-record-reconnect b/bash-scripts/rip-record-reconnect
--- a/bash-scripts/rip-record-reconnect
+++ b/bash-scripts/rip-record-reconnect
@@ -35,21 +35,19 @@ third_arg_validated="^[0-9]{2}:[0-9]{2}:[0-9]{2}$" # matches: 00:00:00
 tflag="$2"     # second argument should be: -t
 duration="$3"  # third argument should be in this format: 00:00:00
 
-if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"       # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+if [[ $# -eq 1 ]]; then                               # + one argument is passed to the script
+	if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
+		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-elif [[ $# -eq 3 ]]; then                             # - three arguments are passed to the script, validate user input
+elif [[ $# -eq 3 ]]; then                             # + three arguments are passed to the script, validate user input
 	if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
-		printf "%s\n" "'$1 $2 $3' invalid input"        # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+		printf "%s\n%s\n" "'$1 $2 $3' invalid input" "$script_usage" # + display invalid user input with error message
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
-   printf "%s\n" "$script_usage"                      # + display script usage
-	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
+else [[ $# -eq 0 ]]                                   # + no arguments are passed to the script
+   printf "%s\n" "$script_usage"                      # - display script usage
+	exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
 fi
 
 shopt -s extglob # enable shell globbing 
@@ -122,8 +120,8 @@ done
 }
 
 #+========================================================+#
-# case statement with regular expression                   #
-# + to execute ffmpeg commands based on matching url       #
+# + case statement with regular expression                 #
+# - to execute ffmpeg commands based on matching url       #
 #+========================================================+#
 
 case "$videourl" in
