while loop

diff --git a/bash-scripts/rip-record b/bash-scripts/rip-record
--- a/bash-scripts/rip-record
+++ b/bash-scripts/rip-record
@@ -127,12 +127,12 @@ case "$videourl" in
 		recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
 		ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
 		-hide_banner -i "$videourl" -c:v copy -c:a copy $tflag $duration "$recordingfile"
-		if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-           break # break out of the while loop
-           exit "$success" # exit with $success error code
+      if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
+         break # break out of the while loop
+         exit "$success" # exit with $success error code
       fi
 		let count=count+1 # increment count
-		sleep 1
+      sleep 1
       done;;
 	$m3u8)              # m3u8 playlist
 		printf "%s\n" 'url matches: $m3u8 bash pattern'
