while loop

diff --git a/bash-scripts/rip-record b/bash-scripts/rip-record
--- a/bash-scripts/rip-record
+++ b/bash-scripts/rip-record
@@ -231,23 +231,23 @@ case "$videourl" in
          let count=count+1 # increment count
          sleep 1
          done;;
-	$m3u8refuseragent)  # m3u8 referer user agent
-		printf "%s\n" 'url matches: $m3u8refuseragent bash pattern'
-		printf "%s\n" "Recording: '$videourl'"
-      count=0 # set count to zero
-		while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-      recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
-		ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
-		-hide_banner -loglevel error -headers 'Referer: '"$referer"''$'\r\n' \
-		-user-agent "$useragent" -i "$m3u8_grep" \
-		-c:v copy -bsf:a aac_adtstoasc $tflag $duration "$recordingfile"
-      if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-			break # break out of the while loop
-         exit "$success" # exit with $success error code
-		fi
-      let count=count+1 # increment count
-      sleep 1
-	   done;;
+    $m3u8refuseragent)  # m3u8 referer user agent
+         printf "%s\n" 'url matches: $m3u8refuseragent bash pattern'
+         printf "%s\n" "Recording: '$videourl'"
+         count=0 # set count to zero
+         while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
+         recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
+         ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 300 \
+         -hide_banner -loglevel error -headers 'Referer: '"$referer"''$'\r\n' \
+         -user-agent "$useragent" -i "$m3u8_grep" \
+         -c:v copy -bsf:a aac_adtstoasc $tflag $duration "$recordingfile"
+         if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
+         	break # break out of the while loop
+            exit "$success" # exit with $success error code
+         fi
+         let count=count+1 # increment count
+         sleep 1
+         done;;
 	$refuseragent)      # referer user agent
 		printf "%s\n" 'url matches: $refuseragent bash pattern'
 		printf "%s\n" "Recording: '$videourl'"
