rip-play functions

diff --git a/bash-scripts-macosx/rip-play b/bash-scripts-macosx/rip-play
--- a/bash-scripts-macosx/rip-play
+++ b/bash-scripts-macosx/rip-play
@@ -1,66 +1,46 @@
 #!/bin/bash
 
-#+==========================================================+#
-# rip-play - execute ffplay commands based on matching url   #
-#+==========================================================+#
-
-# diagram of how the script works
-# [rip-play] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [ffplay]
-
-#+=========================================================+#
-# exit status and error codes                               #
-#+=========================================================+#
+#+========================================================+#
+# exit status, error codes and script usage                #
+#+========================================================+#
 
 SUCCESS=0      # success exit code
 E_NOARGS=65    # no arguments passed to script
 E_NOMATCH=66   # url not matched by regular expression
 
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
-
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url]"
 
-#+=========================================================+#
-# validate user input for first argument                    #
-# + passed to script	by matching with regular expressions   #
-#+=========================================================+#
-
-first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
-
 #+========================================================+#
-# check if first argument is a url in a text file          #
-# + or a url on the command line                           #
+# + check if first argument is a url in a text file        #
+# - or a url on the command line                           #
 #+========================================================+#
 
-if [[ "$1" =~ \.txt$ ]]; then # - text file passed as first argument to script
-	videourl=$(cat "$1")       # + cat the text file to extract the url
+if [[ "$1" =~ \.txt$ ]]; then # + text file passed as first argument to script
+	videourl=$(cat "$1")       # - cat the text file to extract the url
 else
 	videourl="$1"              # url is on the command line
 fi
 
 #+========================================================+#
-# check if 1 argument is  passed to script                 #
-# + and validate user input                                #
+# + validate user input for first argument                 #
+# - passed to script	                                      #
+# + check if 1 or 3 arguments are passed to script         #
+# - validate user input and enable shell globbing          #
 #+========================================================+#
 
-if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"       # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+first_arg_validated="^(http|https|rtmp|rtmpe)://*"    # matches: http|https|rtmp|rtmpe
+
+if [[ $# -eq 1 ]]; then                               # + one argument is passed to the script
+	if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
+		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
-   printf "%s\n" "$script_usage"                      # + display script usage
-	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
+else [[ $# -eq 0 ]]                                   # + no arguments are passed to the script
+   printf "%s\n" "$script_usage"                      # - display script usage
+	exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
 fi
 
-#+========================================================+#
-# enable shell globbing for pattern matching               #
-#+========================================================+#
-
-shopt -s extglob 
+shopt -s extglob # enable shell globbing 
 
 #+========================================================+#
 # case statement switch on pattern match                   #
@@ -93,76 +73,37 @@ cookienltid=$(printf "%s" "$videourl" | grep -Eo 'nltid=[a-zA-Z0-9&%_*=]*')
 cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*[^/]' | sed 's/^http\(\|s\):\/\///g')
 
 #+========================================================+#
-# case statement with regular expression                   #
-# + to execute ffplay commands based on matching url       #
+# play functions using ffmpeg and rtmpdump                +#
+#+========================================================+#
+
+play () {
+$HOME/bin/ffplay -hide_banner -stats -v panic -x 640 -y 360 "${@:2}" "$1"
+}
+
+play_rtmp () {
+/usr/local/bin/rtmpdump -q -i "$1" | $HOME/bin/ffplay -hide_banner -stats -v panic -x 640 -y 360 -
+}
+
+#+========================================================+#
+# + case statement with regular expression                 #
+# - to execute ffplay commands based on matching url       #
 #+========================================================+#
 
 case "$videourl" in
-	$videofile)         # video file
-		printf "%s\n" 'url matches: $videofile bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 "$videourl";;
-	$m3u8)              # m3u8 playlist
-		printf "%s\n" 'url matches: $m3u8 bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 "$videourl" 2>&1 | sed '/\[/d';;
-	$cookiem3u8)        # cookie m3u8
-		printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 -loglevel panic -cookies "$cookienltid; path=/; $cookiedomain;" "$videourl";;
-	$videoqmark)         # video link and question mark
-		printf "%s\n" 'url matches: $videoqmark bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 -loglevel error "$videourl";;
-	$xforward)          # xforward
-		printf "%s\n" 'url matches: $xforward bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 -headers 'X-Forwarded-For: '"$xforwardip"''$'\r\n' "$videofile_grep";;
-	$useref)            # useragent referer
-		printf "%s\n" 'url matches: $useref bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner  -x 640 -y 360 -user-agent "$useragent" -headers 'Referer: '"$referer"''$'\r\n' "$videofile_grep";;
-	$viduseragent)     # user agent 
-		printf "%s\n" 'url matches: $viduseragent bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 -loglevel panic -user-agent "$useragent" "$videofile_grep";;
-	$useragentreferer) # useragent referer
-		printf "%s\n" 'url matches: $useragentreferer bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 -loglevel error -user-agent "$useragent" \
-		-headers 'Referer: '"$referer"''$'\r\n' "$videofile_grep";;
-	$refuseragent)      # referer user agent
-		printf "%s\n" 'url matches: $refuseragent bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 -loglevel error -headers 'Referer: '"$referer"''$'\r\n' \
-		-user-agent "$useragent" "$videofile_grep";;
-	$rtmp)              # rtmp
-		printf "%s\n" 'url matches: $rtmp bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/rtmpdump -q -i "$videourl" | $HOME/bin/ffplay -hide_banner -x 640 -y 360 -;;
-	$cookiem3u8uagent)  # cookie m3u8 useragent
-		printf "%s\n" 'url matches: $cookiem3u8uagent bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 -loglevel panic -user-agent "$useragent2" \
-		-cookies "$cookieurl; path=/; $cookiedomain;" "$videofile_grep";;
-	$http)              # http
-		printf "%s\n" 'url matches: $http bash pattern'
-		printf "%s\n" "Playing: a'$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 "$videourl";;
-	*)                  # wildcard
-		printf "%s\n" 'url matches: * bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		$HOME/bin/ffplay -hide_banner -x 640 -y 360 "$videourl";;
-esac 
+  $videofile) play "$videourl";;
+  $m3u8) play "$videourl";;
+  $cookiem3u8) play "$videourl" -cookies "$cookienltid; path=/; $cookiedomain;";;
+  $videoqmark) play "$videourl";;
+  $xforward) play "$videofile_grep" -headers 'X-Forwarded-For: '"$xforwardip"''$'\r\n';;
+  $useref) play "$videofile_grep" -user-agent "$useragent" -headers 'Referer: '"$referer"''$'\r\n';;
+  $viduseragent) play "$videofile_grep" -user-agent "$useragent";;
+  $useragentreferer) play "$videofile_grep" -user-agent "$useragent" -headers 'Referer: '"$referer"''$'\r\n';;
+  $refuseragent) play "$videofile_grep" -headers 'Referer: '"$referer"''$'\r\n' -user-agent "$useragent";;
+  $rtmp) play_rtmp "$videourl";;
+  $cookiem3u8uagent) play "$videofile_grep" -user-agent "$useragent2" -cookies "$cookieurl; path=/; $cookiedomain;";;
+  $http) play "$videourl";;
+  *) play "$videourl";;
+esac
 
-#+========================================================+#
-# turn off shell globbing                                  #
-#+========================================================+#
-
-shopt -u extglob 
-
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+shopt -u extglob # turn off shell globbing
+exit "$SUCCESS" # exit status SUCCESS if script runs without errors
