rip-vlc

diff --git a/bash-scripts-macosx/rip-vlc b/bash-scripts-macosx/rip-vlc
--- a/bash-scripts-macosx/rip-vlc
+++ b/bash-scripts-macosx/rip-vlc
@@ -1,66 +1,46 @@
 #!/bin/bash
 
-#+==========================================================+#
-# rip-vlc - execute vlc commands based on matching url       #
-#+==========================================================+#
-
-# diagram of how the script works
-# [rip-vlc] > [(text file with url|url on command line)] > [case-statement -match url] > [grep -extract strings] > [vlc]
-
-#+=========================================================+#
-# exit status and error codes                               #
-#+=========================================================+#
+#+========================================================+#
+# exit status, error codes and script usage                #
+#+========================================================+#
 
 SUCCESS=0      # success exit code
 E_NOARGS=65    # no arguments passed to script
 E_NOMATCH=66   # url not matched by regular expression
 
-#+=========================================================+#
-# display script usage when script is run with no arguments #
-# + or when invalid input is entered by the user            #
-#+=========================================================+#
-
 script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/video-url]"
 
-#+=========================================================+#
-# validate user input for first argument                    #
-# + passed to script	by matching with regular expressions   #
-#+=========================================================+#
-
-first_arg_validated="^(http|https|rtmp|rtmpe)://*" # matches: http|https|rtmp|rtmpe
-
 #+========================================================+#
-# check if first argument is a url in a text file          #
-# + or a url on the command line                           #
+# + check if first argument is a url in a text file        #
+# - or a url on the command line                           #
 #+========================================================+#
 
-if [[ "$1" =~ \.txt$ ]]; then # - text file passed as first argument to script
-	videourl=$(cat "$1")       # + cat the text file to extract the url
+if [[ "$1" =~ \.txt$ ]]; then # + text file passed as first argument to script
+	videourl=$(cat "$1")       # - cat the text file to extract the url
 else
 	videourl="$1"              # url is on the command line
 fi
 
 #+========================================================+#
-# check if 1 argument is  passed to script                 #
-# + and validate user input                                #
+# + validate user input for first argument                 #
+# + passed to script                                       #
+# + check if 1 argument is passed to script                #
+# - and validate user input                                #
 #+========================================================+#
 
-if [[ $# -eq 1 ]]; then                               # - one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n" "'$videourl' invalid input"       # + display invalid user input with error message
-		printf "%s\n" "$script_usage"                   # + display script usage
-		exit "$E_NOMATCH"                               # + exit with E_NOMATCH error code
+first_arg_validated="^(http|https|rtmp|rtmpe)://*"    # matches: http|https|rtmp|rtmpe
+
+if [[ $# -eq 1 ]]; then                               # + one argument is passed to the script
+	if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
+		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
+		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
 	fi
-else [[ $# -eq 0 ]]                                   # - no arguments are passed to the script
-   printf "%s\n" "$script_usage"                      # + display script usage
-	exit "$E_NOARGS"                                   # + exit with E_NOARGS error code
+else [[ $# -eq 0 ]]                                   # + no arguments are passed to the script
+   printf "%s\n" "$script_usage"                      # - display script usage
+	exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
 fi
 
-#+========================================================+#
-# enable shell globbing for pattern matching               #
-#+========================================================+#
-
-shopt -s extglob 
+shopt -s extglob # enable shell globbing 
 
 #+========================================================+#
 # case statement switch on pattern match                   #
@@ -97,69 +77,26 @@ cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*
 # + to execute vlc commands based on matching url          #
 #+========================================================+#
 
+vlc_mac="/Applications/VLC.app/Contents/MacOS/VLC"
+wget_mac="/usr/local/bin/wget"
+rtmpdump_mac="/usr/local/bin/rtmpdump"
+
 case "$videourl" in
-	$videofile)         # video file
-		printf "%s\n" 'url matches: $videofile bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/Applications/VLC.app/Contents/MacOS/VLC "$videourl";;
-	$m3u8)              # m3u8 playlist
-		printf "%s\n" 'url matches: $m3u8 bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/Applications/VLC.app/Contents/MacOS/VLC "$videourl";;
-	$cookiem3u8)        # cookie m3u8
-		printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/wget -c --header="cookie: $cookienltid","path=/: $cookiedomain" "$videourl" -O- | /Applications/VLC.app/Contents/MacOS/VLC fd://0;;
-	$videoqmark)         # video link and question mark
-		printf "%s\n" 'url matches: $videoqmark bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-	   /Applications/VLC.app/Contents/MacOS/VLC "$videourl";;
-	$xforward)          # xforward
-		printf "%s\n" 'url matches: $xforward bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/wget -c --header="X-Forwarded-For: $xforwardip" "$videofile_grep" -O- | /Applications/VLC.app/Contents/MacOS/VLC fd://0;;
-	$useref)            # useragent referer
-		printf "%s\n" 'url matches: $useref bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/wget -c -U "$useragent" --header="Referer: $referer" "$videofile_grep" -O- | /Applications/VLC.app/Contents/MacOS/VLC fd://0;;
-	$viduseragent)     # user agent 
-		printf "%s\n" 'url matches: $viduseragent bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/wget -c -U "$useragent" "$videofile_grep" -O- | /Applications/VLC.app/Contents/MacOS/VLC fd://0;;
-	$useragentreferer) # useragent referer
-		printf "%s\n" 'url matches: $useragentreferer bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/wget -c -U "$useragent" --header="Referer: $referer" "$videofile_grep" -O- | /Applications/VLC.app/Contents/MacOS/VLC fd://0;;
-	$refuseragent)      # referer user agent
-		printf "%s\n" 'url matches: $refuseragent bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/wget -c --header="Referer: $referer" -U "$useragent" "$videofile_grep" -O- | /Applications/VLC.app/Contents/MacOS/VLC fd://0;;
-	$rtmp)              # rtmp
-		printf "%s\n" 'url matches: $rtmp bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/rtmpdump -q -i "$videourl" | /Applications/VLC.app/Contents/MacOS/VLC fd://0;;
-	$cookiem3u8uagent)  # cookie m3u8 useragent
-		printf "%s\n" 'url matches: $cookiem3u8uagent bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/usr/local/bin/wget -c -U "$useragent2" --header="cookie: $cookieurl","path=/: $cookiedomain" "$videofile_grep" -O- | /Applications/VLC.app/Contents/MacOS/VLC  fd://0;;
-	$http)              # http
-		printf "%s\n" 'url matches: $http bash pattern'
-		printf "%s\n" "Playing: a'$videourl'"
-		/Applications/VLC.app/Contents/MacOS/VLC "$videourl";;
-	*)                  # wildcard
-		printf "%s\n" 'url matches: * bash pattern'
-		printf "%s\n" "Playing: '$videourl'"
-		/Applications/VLC.app/Contents/MacOS/VLC "$videourl";;
+	$videofile) "$vlc_mac" "$videourl";;
+	$m3u8) "$vlc_mac" "$videourl";;
+	$cookiem3u8) "$wget_mac" -c --header="cookie: $cookienltid","path=/: $cookiedomain" "$videourl" -O- | "$vlc_mac" fd://0;;
+	$videoqmark) "$vlc_mac" "$videourl";;
+	$xforward) "$wget_mac" -c --header="X-Forwarded-For: $xforwardip" "$videofile_grep" -O- | "$vlc_mac" fd://0;;
+	$useref) "$wget_mac" -c -U "$useragent" --header="Referer: $referer" "$videofile_grep" -O- | "$vlc_mac" fd://0;;
+	$viduseragent) "$wget_mac" -c -U "$useragent" "$videofile_grep" -O- | "$vlc_mac" fd://0;;
+	$useragentreferer) "$wget_mac" -c -U "$useragent" --header="Referer: $referer" "$videofile_grep" -O- | "$vlc_mac" fd://0;;
+	$refuseragent) "$wget_mac" -c --header="Referer: $referer" -U "$useragent" "$videofile_grep" -O- | "$vlc_mac" fd://0;;
+	$rtmp) "$rtmpdump_mac" -q -i "$videourl" | "$vlc_mac" fd://0;;
+	$cookiem3u8uagent) "$wget_mac" -c -U "$useragent2" --header="cookie: $cookieurl","path=/: $cookiedomain" "$videofile_grep" -O- \
+   | "$vlc_mac" fd://0;;
+	$http) "$vlc_mac" "$videourl";;
+	*) "$vlc_mac" "$videourl";;
 esac 
 
-#+========================================================+#
-# turn off shell globbing                                  #
-#+========================================================+#
-
-shopt -u extglob 
-
-#+========================================================+#
-# exit status SUCCESS if script runs without errors        #
-#+========================================================+#
-
-exit "$SUCCESS"
+shopt -u extglob # turn off shell globbing
+exit "$SUCCESS" # exit status SUCCESS if script runs without errors
