rip-ssh

diff --git a/bash-scripts-macosx/rip-ssh b/bash-scripts-macosx/rip-ssh
--- a/bash-scripts-macosx/rip-ssh
+++ b/bash-scripts-macosx/rip-ssh
@@ -17,9 +17,9 @@ script_usage="Usage: $(basename "$0") [ssh server] [(http|https|rtmp|rtmpe)://ex
 #+=========================================================+#
 
 if [[ "$2" =~ \.txt$ ]]; then # - text file passed as second argument to script
-	videourl=$(cat "$2")       # + cat the text file to extract the url
+   videourl=$(cat "$2")       # + cat the text file to extract the url
 else
-	videourl="$2"              # url is on the command line
+   videourl="$2"              # url is on the command line
 fi
 
 #+=========================================================+#
@@ -41,18 +41,18 @@ tflag="$3"     # third argument should be: -t
 duration="$4"  # fourth argument should be in this format: 00:00:00
 
 if [[ $# -eq 2 ]]; then                                # - two argument are passed to the script
-	if ! [[ $videourl =~ $second_arg_validated ]]; then # + if videourl doesnt match validation regular expression
-		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # + display invalid user input with error message
-		exit "$E_NOMATCH"                                # + exit with E_NOMATCH error code
-	fi
+   if ! [[ $videourl =~ $second_arg_validated ]]; then # + if videourl doesnt match validation regular expression
+      printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # + display invalid user input with error message
+      exit "$E_NOMATCH"                                # + exit with E_NOMATCH error code
+   fi
 elif [[ $# -eq 4 ]]; then                              # - three arguments are passed to the script, validate user input
-	if ! [[ $sshserver =~ $first_arg_validated && $videourl =~ $second_arg_validated && $tflag =~ $third_arg_validated && $duration =~ $fourth_arg_validated ]]; then
-		printf "%s\n%s\n" "'$1 $2 $3 $4' invalid input" "$script_usage" # + display invalid user input with error message
-		exit "$E_NOMATCH"                                # + exit with E_NOMATCH error code
-	fi
+   if ! [[ $sshserver =~ $first_arg_validated && $videourl =~ $second_arg_validated && $tflag =~ $third_arg_validated && $duration =~ $fourth_arg_validated ]]; then
+      printf "%s\n%s\n" "'$1 $2 $3 $4' invalid input" "$script_usage" # + display invalid user input with error message
+      exit "$E_NOMATCH"                                # + exit with E_NOMATCH error code
+   fi
 else [[ $# -eq 0 ]]                                    # - no arguments are passed to the script
    printf "%s\n" "$script_usage"                       # + display script usage
-	exit "$E_NOARGS"                                    # + exit with E_NOARGS error code
+   exit "$E_NOARGS"                                    # + exit with E_NOARGS error code
 fi
 
 shopt -s extglob # enable shell globbing 
