rip-record

diff --git a/bash-scripts-macosx/rip-record b/bash-scripts-macosx/rip-record
--- a/bash-scripts-macosx/rip-record
+++ b/bash-scripts-macosx/rip-record
@@ -114,7 +114,6 @@ xforwardip=$(printf "%s" "$videourl" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1
 cookieurl=$(printf "%s" "$videourl" | grep -Eo 'nltid=[a-zA-Z0-9&%_*=]*')
 cookiedomain=$(printf "%s" "$videourl" | grep -Eo '(http|https)://[a-zA-Z0-9.-]*[^/]' | sed 's/^http\(\|s\):\/\///g')
 
-
 #+========================================================+#
 # case statement with regular expression                   #
 # + to execute ffmpeg commands based on matching url       #
@@ -145,6 +144,22 @@ case "$videourl" in
        $HOME/bin/ffmpeg \
        -hide_banner -i "$videourl" \
        -c:v copy -c:a copy $tflag $duration "$recordingfile" 2>&1 | sed '/\[/d'
+       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
+          break # break out of the while loop
+          exit "$SUCCESS" # exit with $SUCCESS error code
+       fi
+       let count=count+1 # increment count
+       sleep 1
+       done;;
+  $cookiem3u8)        # cookie m3u8
+       printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
+       printf "%s\n" "Recording: '$videourl'"
+       count=0 # set count to zero
+       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
+       recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
+       $HOME/bin/ffmpeg \
+       -hide_banner -loglevel panic -cookies "$cookieurl; path=/; $cookiedomain;" -i "$videourl" \
+       -c:v copy -c:a copy $tflag $duration "$recordingfile"
        if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
           break # break out of the while loop
           exit "$SUCCESS" # exit with $SUCCESS error code
@@ -274,22 +289,6 @@ case "$videourl" in
        recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
        /usr/local/bin/rtmpdump -q -i "$videourl" | $HOME/bin/ffmpeg \
        -hide_banner -i - -c:v copy -c:a copy $tflag $duration "$recordingfile"
-       if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
-          break # break out of the while loop
-          exit "$SUCCESS" # exit with $SUCCESS error code
-       fi
-       let count=count+1 # increment count
-       sleep 1
-       done;;
-  $cookiem3u8)        # cookie m3u8
-       printf "%s\n" 'url matches: $cookiem3u8 bash pattern'
-       printf "%s\n" "Recording: '$videourl'"
-       count=0 # set count to zero
-       while [[ "$count" < 3 ]]; do # while count is less than 3 run the script
-       recordingfile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mkv" 
-       $HOME/bin/ffmpeg \
-       -hide_banner -loglevel panic -cookies "$cookieurl; path=/; $cookiedomain;" -i "$videourl" \
-       -c:v copy -c:a copy $tflag $duration "$recordingfile"
        if [[ $? -eq 0 ]]; then # check the ffmpeg exit code is 0, which means the recording worked
           break # break out of the while loop
           exit "$SUCCESS" # exit with $SUCCESS error code
