rip-stream

diff --git a/bash-scripts-macosx/rip-stream b/bash-scripts-macosx/rip-stream
--- a/bash-scripts-macosx/rip-stream
+++ b/bash-scripts-macosx/rip-stream
@@ -17,9 +17,9 @@ script_usage="Usage: $(basename "$0") [(http|https|rtmp|rtmpe)://example.com/vid
 #+========================================================+#
 
 if [[ "$1" =~ \.txt$ ]]; then # + text file passed as first argument to script
-	videourl=$(cat "$1")       # - cat the text file to extract the url
+   videourl=$(cat "$1")       # - cat the text file to extract the url
 else
-	videourl="$1"              # url is on the command line
+   videourl="$1"              # url is on the command line
 fi
 
 #+========================================================+#
@@ -39,18 +39,18 @@ tflag="$2"     # second argument should be: -t
 duration="$3"  # third argument should be in this format: 00:00:00
 
 if [[ $# -eq 1 ]]; then                               # + one argument is passed to the script
-	if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
-		printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
-		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
-	fi
+   if ! [[ $videourl =~ $first_arg_validated ]]; then # - if videourl doesnt match validation regular expression
+      printf "%s\n%s\n" "'$videourl' invalid input" "$script_usage" # - display invalid user input with error message
+      exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
+   fi
 elif [[ $# -eq 3 ]]; then                             # + three arguments are passed to the script, validate user input
-	if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
-		printf "%s\n%s\n" "'$1 $2 $3' invalid input" "$script_usage" # - display invalid user input with error message
-		exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
-	fi
+   if ! [[ $videourl =~ $first_arg_validated && $tflag =~ $second_arg_validated && $duration =~ $third_arg_validated ]]; then
+      printf "%s\n%s\n" "'$1 $2 $3' invalid input" "$script_usage" # - display invalid user input with error message
+      exit "$E_NOMATCH"                               # - exit with E_NOMATCH error code
+   fi
 else [[ $# -eq 0 ]]                                   # + no arguments are passed to the script
    printf "%s\n" "$script_usage"                      # - display script usage
-	exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
+   exit "$E_NOARGS"                                   # - exit with E_NOARGS error code
 fi
 
 shopt -s extglob # enable shell globbing 
